---
- name: Setup directories and execute script on remote Linux server
  hosts: your_target_host_group_or_hostname
  become: yes  # Ensure elevated privileges

  tasks:
    - name: Create main directory
      ansible.builtin.file:
        path: /app/devops_admin
        state: directory
        mode: '0755'
      tags: directory_setup

    - name: Create subdirectories (bin, log, adhoc)
      ansible.builtin.file:
        path: "/app/devops_admin/{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - bin
        - log
        - adhoc
      tags: directory_setup

    - name: Execute oracle-DB_conf_report.sh and log output
      ansible.builtin.shell: "/app/devops/bin/oracle-DB_conf_report.sh"
      register: script_output
      failed_when: >
        ("No such file or directory" in script_output.stdout) or
        (script_output.stderr != '') or
        (script_output.rc == 10)

    - name: Save script output to log file
      ansible.builtin.copy:
        content: "{{ script_output.stdout }}"
        dest: "/app/devops/log/oracle-DB_conf_report.log"
        mode: '0644'
      tags: script_execution
