- name: Copy /app directory from origin to destiny host
  hosts: all
  gather_facts: no
  vars:
    origin_host: origin_host_ssh_details # e.g., user@host1
    destiny_host: destiny_host_ssh_details # e.g., user@host2
    origin_path: /app/
    destiny_path: /app/
  tasks:
    - name: Rsync from origin to destiny host
      command: >
        rsync -avz -e "ssh -o StrictHostKeyChecking=no" --rsync-path="sudo rsync"
        {{ origin_host }}:{{ origin_path }} {{ destiny_host }}:{{ destiny_path }}
      delegate_to: localhost
