- name: Encrypt a password with Ansible Vault
  hosts: all
  gather_facts: no
  vars_prompt:
    - name: user_password
      prompt: "Enter the password to encrypt"
      private: yes

  tasks:
    - name: Check if the Vault password file exists
      ansible.builtin.stat:
        path: /app/ansible/vaultPass.conf
      register: vault_pass_file

    - name: Fail if the Vault password file does not exist
      ansible.builtin.fail:
        msg: "The Vault password file /app/ansible/vaultPass.conf does not exist."
      when: not vault_pass_file.stat.exists

    - name: Encrypt the password
      ansible.builtin.shell: 
        cmd: "ansible-vault encrypt_string '{{ user_password }}' --vault-password-file /app/ansible/vaultPass.conf --name 'encrypted_password'"
      register: encrypted_output
      changed_when: false

    - name: Show encrypted password
      ansible.builtin.debug:
        msg: "{{ encrypted_output.stdout }}"

    - name: Write encrypted password to file
      ansible.builtin.copy:
        content: "{{ encrypted_output.stdout }}"
        dest: /app/ansible/encryptedPass.conf
        mode: '0600'
      delegate_to: localhost
      register: encrypted_file_result

    - name: Confirm encrypted password file exists
      ansible.builtin.stat:
        path: /app/ansible/encryptedPass.conf
      register: encrypted_pass_file

    - name: Fail if the encrypted password file does not exist after write attempt
      ansible.builtin.fail:
        msg: "Failed to create or verify the encrypted password file /app/ansible/encryptedPass.conf."
      when: not encrypted_pass_file.stat.exists
